// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ftgaoadnxrodfgtsftoq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ0Z2FvYWRueHJvZGZndHNmdG9xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI5ODk0MjEsImV4cCI6MjA4ODU2NTQyMX0.K9fLzJdONqr3i_BRz44qy73BYbghCb6N4zbNRYD8H6E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});